/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/alu_top.v:3" *)
module alu_top(A, B, opcode, result, carry, zero, overflow);
  (* src = "../rtl/alu_top.v:26" *)
  wire [8:0] _000_;
  (* src = "../rtl/alu_top.v:38" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire [2:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire [3:0] _017_;
  wire [1:0] _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire [3:0] _021_;
  wire [1:0] _022_;
  wire [3:0] _023_;
  wire [1:0] _024_;
  wire [3:0] _025_;
  wire [1:0] _026_;
  wire [3:0] _027_;
  wire [1:0] _028_;
  wire [3:0] _029_;
  wire [1:0] _030_;
  wire [3:0] _031_;
  wire [1:0] _032_;
  wire [3:0] _033_;
  wire [1:0] _034_;
  wire [3:0] _035_;
  wire [1:0] _036_;
  wire _037_;
  wire _038_;
  wire [2:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "../rtl/alu_top.v:47" *)
  wire [7:0] _047_;
  (* src = "../rtl/alu_top.v:41" *)
  wire [7:0] _048_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:432" *)
  wire [2:0] _049_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:428" *)
  wire _050_;
  wire _051_;
  wire _052_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:432" *)
  wire [63:0] _053_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:428" *)
  wire [7:0] _054_;
  (* src = "../rtl/alu_top.v:32" *)
  wire [8:0] _055_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:203" *)
  wire [8:0] _056_;
  wire [8:0] _057_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)
  wire _058_;
  (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)
  wire _059_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:258" *)
  wire [8:0] _060_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:203" *)
  wire [8:0] _061_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [8:0] _062_;
  wire [8:0] _063_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _064_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _065_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _066_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _067_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _068_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _069_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _070_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)
  wire _071_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)
  wire _072_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)
  wire _073_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)
  wire _074_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)
  wire _075_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)
  wire _076_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)
  wire _077_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)
  wire _078_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _079_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _080_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _081_;
  (* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)
  wire _082_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)
  wire [8:0] _083_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _084_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _085_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _086_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _087_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _088_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _089_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _090_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)
  wire _091_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)
  wire _092_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)
  wire _093_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)
  wire _094_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)
  wire _095_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)
  wire _096_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)
  wire _097_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)
  wire _098_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _099_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _100_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _101_;
  (* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)
  wire _102_;
  (* src = "../rtl/alu_top.v:5" *)
  input [7:0] A;
  (* src = "../rtl/alu_top.v:6" *)
  input [7:0] B;
  (* src = "../rtl/alu_top.v:10" *)
  output carry;
  (* src = "../rtl/alu_top.v:7" *)
  input [2:0] opcode;
  (* src = "../rtl/alu_top.v:12" *)
  output overflow;
  (* src = "../rtl/alu_top.v:9" *)
  output [7:0] result;
  (* src = "../rtl/alu_top.v:11" *)
  output zero;
  assign _040_ = _009_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23" *)  _039_[2];
  assign _041_ = _010_ |(* src = "../rtl/alu_top.v:49|../rtl/alu_top.v:23" *)  _039_[2];
  assign _042_ = _011_ |(* src = "../rtl/alu_top.v:46|../rtl/alu_top.v:23" *)  _039_[2];
  assign _043_ = _012_ |(* src = "../rtl/alu_top.v:43|../rtl/alu_top.v:23" *)  _039_[2];
  assign _009_ = _039_[0] |(* src = "../rtl/alu_top.v:40|../rtl/alu_top.v:23" *)  _039_[1];
  assign _044_ = _009_ |(* src = "../rtl/alu_top.v:40|../rtl/alu_top.v:23" *)  opcode[2];
  assign _010_ = opcode[0] |(* src = "../rtl/alu_top.v:37|../rtl/alu_top.v:23" *)  _039_[1];
  assign _045_ = _010_ |(* src = "../rtl/alu_top.v:37|../rtl/alu_top.v:23" *)  opcode[2];
  assign _011_ = _039_[0] |(* src = "../rtl/alu_top.v:31|../rtl/alu_top.v:23" *)  opcode[1];
  assign _046_ = _011_ |(* src = "../rtl/alu_top.v:31|../rtl/alu_top.v:23" *)  opcode[2];
  assign _014_ = _013_[0] | _013_[1];
  assign _002_ = _014_ | _013_[2];
  assign _050_ = _015_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _049_[2];
  assign _016_ = _002_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _051_;
  assign _058_ = _016_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _052_;
  assign _017_[0] = _053_[1] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[9];
  assign _017_[1] = _053_[17] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[25];
  assign _017_[2] = _053_[33] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[41];
  assign _017_[3] = _053_[49] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[57];
  assign _018_[0] = _017_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _017_[1];
  assign _018_[1] = _017_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _017_[3];
  assign _054_[1] = _018_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _018_[1];
  assign _019_[1] = _053_[23] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[31];
  assign _019_[2] = _053_[39] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[47];
  assign _019_[3] = _053_[55] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[63];
  assign _020_[0] = _019_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _019_[3];
  assign _054_[7] = _020_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _020_[1];
  assign _021_[0] = _053_[6] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[14];
  assign _021_[1] = _053_[22] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[30];
  assign _021_[2] = _053_[38] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[46];
  assign _021_[3] = _053_[54] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[62];
  assign _022_[0] = _021_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _021_[1];
  assign _022_[1] = _021_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _021_[3];
  assign _054_[6] = _022_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _022_[1];
  assign _023_[0] = _053_[5] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[13];
  assign _023_[1] = _053_[21] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[29];
  assign _023_[2] = _053_[37] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[45];
  assign _023_[3] = _053_[53] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[61];
  assign _024_[0] = _023_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _023_[1];
  assign _024_[1] = _023_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _023_[3];
  assign _054_[5] = _024_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _024_[1];
  assign _025_[0] = _053_[4] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[12];
  assign _025_[1] = _053_[20] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[28];
  assign _025_[2] = _053_[36] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[44];
  assign _025_[3] = _053_[52] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[60];
  assign _026_[0] = _025_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _025_[1];
  assign _026_[1] = _025_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _025_[3];
  assign _054_[4] = _026_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _026_[1];
  assign _027_[0] = _053_[3] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[11];
  assign _027_[1] = _053_[19] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[27];
  assign _027_[2] = _053_[35] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[43];
  assign _027_[3] = _053_[51] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[59];
  assign _028_[0] = _027_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _027_[1];
  assign _028_[1] = _027_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _027_[3];
  assign _054_[3] = _028_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _028_[1];
  assign _029_[0] = _053_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[10];
  assign _029_[1] = _053_[18] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[26];
  assign _029_[2] = _053_[34] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[42];
  assign _029_[3] = _053_[50] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[58];
  assign _030_[0] = _029_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _029_[1];
  assign _030_[1] = _029_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _029_[3];
  assign _054_[2] = _030_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _030_[1];
  assign _031_[1] = _053_[16] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[24];
  assign _031_[2] = _053_[32] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[40];
  assign _031_[3] = _053_[48] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _053_[56];
  assign _032_[0] = _031_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _031_[1];
  assign _032_[1] = _031_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _031_[3];
  assign _054_[0] = _032_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:441" *)  _032_[1];
  assign _013_[2] = _003_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _004_;
  assign _013_[1] = _005_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _006_;
  assign _013_[0] = _007_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _008_;
  assign _033_[3] = _051_ |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _052_;
  assign _034_[0] = _013_[2] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _013_[1];
  assign _034_[1] = _013_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _033_[3];
  assign _059_ = _034_[0] |(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *)  _034_[1];
  assign _035_[0] = result[0] |(* src = "../rtl/alu_top.v:57" *)  result[1];
  assign _035_[1] = result[2] |(* src = "../rtl/alu_top.v:57" *)  result[3];
  assign _035_[2] = result[4] |(* src = "../rtl/alu_top.v:57" *)  result[5];
  assign _035_[3] = result[6] |(* src = "../rtl/alu_top.v:57" *)  result[7];
  assign _036_[0] = _035_[0] |(* src = "../rtl/alu_top.v:57" *)  _035_[1];
  assign _036_[1] = _035_[2] |(* src = "../rtl/alu_top.v:57" *)  _035_[3];
  assign _037_ = _036_[0] |(* src = "../rtl/alu_top.v:57" *)  _036_[1];
  assign _012_ = opcode[0] |(* src = "../rtl/alu_top.v:25|../rtl/alu_top.v:23" *)  opcode[1];
  assign _038_ = _012_ |(* src = "../rtl/alu_top.v:25|../rtl/alu_top.v:23" *)  opcode[2];
  assign zero = ~(* src = "../rtl/alu_top.v:57" *) _037_;
  assign _003_ = ~(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23" *) _040_;
  assign _004_ = ~(* src = "../rtl/alu_top.v:49|../rtl/alu_top.v:23" *) _041_;
  assign _005_ = ~(* src = "../rtl/alu_top.v:46|../rtl/alu_top.v:23" *) _042_;
  assign _006_ = ~(* src = "../rtl/alu_top.v:43|../rtl/alu_top.v:23" *) _043_;
  assign _007_ = ~(* src = "../rtl/alu_top.v:40|../rtl/alu_top.v:23" *) _044_;
  assign _008_ = ~(* src = "../rtl/alu_top.v:37|../rtl/alu_top.v:23" *) _045_;
  assign _051_ = ~(* src = "../rtl/alu_top.v:31|../rtl/alu_top.v:23" *) _046_;
  assign _052_ = ~(* src = "../rtl/alu_top.v:25|../rtl/alu_top.v:23" *) _038_;
  assign carry = _058_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _050_ : 1'hx;
  assign result[0] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[0] : 1'hx;
  assign result[1] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[1] : 1'hx;
  assign result[2] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[2] : 1'hx;
  assign result[3] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[3] : 1'hx;
  assign result[4] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[4] : 1'hx;
  assign result[5] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[5] : 1'hx;
  assign result[6] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[6] : 1'hx;
  assign result[7] = _059_ ? (* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:445" *) _054_[7] : 1'hx;
  assign _047_[0] = ~(* src = "../rtl/alu_top.v:47" *) A[0];
  assign _047_[1] = ~(* src = "../rtl/alu_top.v:47" *) A[1];
  assign _047_[2] = ~(* src = "../rtl/alu_top.v:47" *) A[2];
  assign _047_[3] = ~(* src = "../rtl/alu_top.v:47" *) A[3];
  assign _047_[4] = ~(* src = "../rtl/alu_top.v:47" *) A[4];
  assign _047_[5] = ~(* src = "../rtl/alu_top.v:47" *) A[5];
  assign _047_[6] = ~(* src = "../rtl/alu_top.v:47" *) A[6];
  assign _047_[7] = ~(* src = "../rtl/alu_top.v:47" *) A[7];
  assign _060_[0] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[0];
  assign _060_[1] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[1];
  assign _060_[2] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[2];
  assign _060_[3] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[3];
  assign _060_[4] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[4];
  assign _060_[5] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[5];
  assign _060_[6] = ~(* src = "../rtl/alu_top.v:26|<techmap.v>:258" *) B[6];
  assign _060_[7] = ~(* src = "../rtl/alu_top.v:32|<techmap.v>:258" *) B[7];
  assign _048_[0] = A[0] |(* src = "../rtl/alu_top.v:41" *)  B[0];
  assign _048_[1] = A[1] |(* src = "../rtl/alu_top.v:41" *)  B[1];
  assign _048_[2] = A[2] |(* src = "../rtl/alu_top.v:41" *)  B[2];
  assign _048_[3] = A[3] |(* src = "../rtl/alu_top.v:41" *)  B[3];
  assign _048_[4] = A[4] |(* src = "../rtl/alu_top.v:41" *)  B[4];
  assign _048_[5] = A[5] |(* src = "../rtl/alu_top.v:41" *)  B[5];
  assign _048_[6] = A[6] |(* src = "../rtl/alu_top.v:41" *)  B[6];
  assign _048_[7] = A[7] |(* src = "../rtl/alu_top.v:41" *)  B[7];
  assign _039_[2] = opcode[2] ^(* src = "../rtl/alu_top.v:43|../rtl/alu_top.v:23" *)  1'h1;
  assign _039_[1] = opcode[1] ^(* src = "../rtl/alu_top.v:37|../rtl/alu_top.v:23" *)  1'h1;
  assign _039_[0] = opcode[0] ^(* src = "../rtl/alu_top.v:31|../rtl/alu_top.v:23" *)  1'h1;
  assign _049_[2] = _000_[8] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _015_ = _055_[8] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[56] = _000_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[57] = _000_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[58] = _000_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[59] = _000_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[60] = _000_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[61] = _000_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[62] = _000_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[63] = _000_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _052_;
  assign _053_[48] = _055_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[49] = _055_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[50] = _055_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[51] = _055_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[52] = _055_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[53] = _055_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[54] = _055_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[55] = _055_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _051_;
  assign _053_[40] = _001_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[41] = _001_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[42] = _001_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[43] = _001_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[44] = _001_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[45] = _001_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[46] = _001_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[47] = _001_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _008_;
  assign _053_[32] = _048_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[33] = _048_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[34] = _048_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[35] = _048_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[36] = _048_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[37] = _048_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[38] = _048_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[39] = _048_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _007_;
  assign _053_[24] = _000_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[25] = _057_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[26] = _057_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[27] = _057_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[28] = _057_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[29] = _057_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[30] = _057_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[31] = _057_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _006_;
  assign _053_[16] = _047_[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[17] = _047_[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[18] = _047_[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[19] = _047_[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[20] = _047_[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[21] = _047_[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[22] = _047_[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[23] = _047_[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _005_;
  assign _053_[9] = A[0] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _053_[10] = A[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _053_[11] = A[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _053_[12] = A[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _053_[13] = A[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _053_[14] = A[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _019_[0] = A[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _004_;
  assign _031_[0] = A[1] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[1] = A[2] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[2] = A[3] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[3] = A[4] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[4] = A[5] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[5] = A[6] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _053_[6] = A[7] &(* src = "../rtl/alu_top.v:52|../rtl/alu_top.v:23|<techmap.v>:434" *)  _003_;
  assign _001_[0] = A[0] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[0];
  assign _001_[1] = A[1] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[1];
  assign _001_[2] = A[2] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[2];
  assign _001_[3] = A[3] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[3];
  assign _001_[4] = A[4] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[4];
  assign _001_[5] = A[5] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[5];
  assign _001_[6] = A[6] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[6];
  assign _001_[7] = A[7] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260" *)  B[7];
  assign _000_[1] = _057_[1] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _001_[0];
  assign _000_[2] = _057_[2] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[1];
  assign _000_[3] = _057_[3] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[2];
  assign _000_[4] = _057_[4] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[3];
  assign _000_[5] = _057_[5] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[4];
  assign _000_[6] = _057_[6] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[5];
  assign _000_[7] = _057_[7] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:263" *)  _056_[6];
  assign _000_[0] = A[0] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[0];
  assign _057_[1] = A[1] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[1];
  assign _057_[2] = A[2] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[2];
  assign _057_[3] = A[3] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[3];
  assign _057_[4] = A[4] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[4];
  assign _057_[5] = A[5] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[5];
  assign _057_[6] = A[6] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[6];
  assign _057_[7] = A[7] ^(* src = "../rtl/alu_top.v:26|<techmap.v>:262" *)  B[7];
  assign _083_[0] = A[0] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[0];
  assign _083_[1] = A[1] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[1];
  assign _083_[2] = A[2] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[2];
  assign _083_[3] = A[3] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[3];
  assign _083_[4] = A[4] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[4];
  assign _083_[5] = A[5] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[5];
  assign _083_[6] = A[6] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[6];
  assign _083_[7] = A[7] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260" *)  _060_[7];
  assign _055_[0] = _062_[0] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  1'h1;
  assign _055_[1] = _063_[1] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[0];
  assign _055_[2] = _063_[2] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[1];
  assign _055_[3] = _063_[3] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[2];
  assign _055_[4] = _063_[4] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[3];
  assign _055_[5] = _063_[5] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[4];
  assign _055_[6] = _063_[6] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[5];
  assign _055_[7] = _063_[7] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[6];
  assign _055_[8] = 1'h1 ^(* src = "../rtl/alu_top.v:32|<techmap.v>:263" *)  _061_[8];
  assign _062_[0] = A[0] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[0];
  assign _063_[1] = A[1] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[1];
  assign _063_[2] = A[2] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[2];
  assign _063_[3] = A[3] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[3];
  assign _063_[4] = A[4] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[4];
  assign _063_[5] = A[5] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[5];
  assign _063_[6] = A[6] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[6];
  assign _063_[7] = A[7] ^(* src = "../rtl/alu_top.v:32|<techmap.v>:262" *)  _060_[7];
  assign _064_ = _057_[1] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _001_[0];
  assign _065_ = _057_[3] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _001_[2];
  assign _066_ = _057_[5] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _001_[4];
  assign _067_ = _057_[7] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _001_[6];
  assign _068_ = _071_ &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _056_[1];
  assign _069_ = _073_ &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _080_;
  assign _070_ = _074_ &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _056_[3];
  assign _071_ = _057_[3] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)  _057_[2];
  assign _072_ = _057_[5] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)  _057_[4];
  assign _073_ = _057_[7] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)  _057_[6];
  assign _074_ = _073_ &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:222" *)  _072_;
  assign _075_ = _072_ &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _056_[3];
  assign _076_ = _057_[2] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _056_[1];
  assign _077_ = _057_[4] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _056_[3];
  assign _078_ = _057_[6] &(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _056_[5];
  assign _056_[1] = _001_[1] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _064_;
  assign _079_ = _001_[3] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _065_;
  assign _080_ = _001_[5] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _066_;
  assign _081_ = _001_[7] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _067_;
  assign _056_[3] = _079_ |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _068_;
  assign _082_ = _081_ |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _069_;
  assign _000_[8] = _082_ |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:221" *)  _070_;
  assign _056_[5] = _080_ |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _075_;
  assign _056_[2] = _001_[2] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _076_;
  assign _056_[4] = _001_[4] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _077_;
  assign _056_[6] = _001_[6] |(* src = "../rtl/alu_top.v:26|<techmap.v>:260|<techmap.v>:229" *)  _078_;
  assign _084_ = _063_[1] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _061_[0];
  assign _085_ = _063_[3] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _083_[2];
  assign _086_ = _063_[5] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _083_[4];
  assign _087_ = _063_[7] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _083_[6];
  assign _088_ = _091_ &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _061_[1];
  assign _089_ = _093_ &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _100_;
  assign _090_ = _094_ &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _061_[3];
  assign _091_ = _063_[3] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)  _063_[2];
  assign _092_ = _063_[5] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)  _063_[4];
  assign _093_ = _063_[7] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)  _063_[6];
  assign _094_ = _093_ &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:222" *)  _092_;
  assign _095_ = _092_ &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _061_[3];
  assign _096_ = _063_[2] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _061_[1];
  assign _097_ = _063_[4] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _061_[3];
  assign _098_ = _063_[6] &(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _061_[5];
  assign _061_[0] = _083_[0] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:212" *)  _062_[0];
  assign _061_[1] = _083_[1] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _084_;
  assign _099_ = _083_[3] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _085_;
  assign _100_ = _083_[5] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _086_;
  assign _101_ = _083_[7] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _087_;
  assign _061_[3] = _099_ |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _088_;
  assign _102_ = _101_ |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _089_;
  assign _061_[8] = _102_ |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:221" *)  _090_;
  assign _061_[5] = _100_ |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _095_;
  assign _061_[2] = _083_[2] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _096_;
  assign _061_[4] = _083_[4] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _097_;
  assign _061_[6] = _083_[6] |(* src = "../rtl/alu_top.v:32|<techmap.v>:260|<techmap.v>:229" *)  _098_;
  assign _033_[2:0] = { _013_[0], _013_[1], _013_[2] };
  assign { _053_[15], _053_[8:7], _053_[0] } = { _019_[0], 2'h0, _031_[0] };
  assign _060_[8] = 1'h1;
  assign { _056_[8:7], _056_[0] } = { 1'h0, _000_[8], _001_[0] };
  assign _049_[1:0] = { _015_, 1'h0 };
  assign _083_[8] = 1'h0;
  assign { _063_[8], _063_[0] } = { 1'h1, _062_[0] };
  assign _061_[7] = _061_[8];
  assign { _057_[8], _057_[0] } = { 1'h0, _000_[0] };
  assign overflow = 1'h0;
endmodule
